version: '3.6'
services:
  postgres:
    container_name: currency-postgres-db
    image: postgres:12
    ports:
      - "5434:5432"
    restart: always
    volumes:
    - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    environment:
      POSTGRES_PASSWORD: postgres